Alexandr satskov
YaBackSchool2021/homework1 pull request #12
Opened 2021-06-08 05:38 UTC by twinkleToes2001

2021-06-08 12:09 UTC, kesha1225 requested changes

2021-06-08 12:09 UTC, kesha1225 commented on alexandr-satskov/README.md
> +Для хранения данных о семейном аккаунте потребуется? создать **новую таблицу family_accounts**, которая будет содержать id создателя, привязанную карту для оплаты и тп.
Наверное лучше вынести фичу из монолита, и там уже иметь свою базу

2021-06-08 12:16 UTC, kesha1225 approved these changes

2021-06-08 12:24 UTC, twinkleToes2001 commented on alexandr-satskov/README.md
> +Для хранения данных о семейном аккаунте потребуется? создать **новую таблицу family_accounts**, которая будет содержать id создателя, привязанную карту для оплаты и тп.
оки доки

2021-06-09 11:25 UTC, dr3w-an commented on alexandr-satskov/README.md
> +Код пишем в микросервисе, НЕ МОНОЛИТ.
почему?

2021-06-09 11:25 UTC, dr3w-an commented on alexandr-satskov/README.md
> +Для хранения данных о семейном аккаунте потребуется? создать **новую таблицу family_accounts**, которая будет содержать id создателя, привязанную карту для оплаты и тп.
@kesha1225 да по большому счёту не обязательно, можно и в монолите. я думаю, такие фундаментальные архитектурные решения стоит по крайней мере аргументировать

2021-06-09 11:25 UTC, dr3w-an commented on alexandr-satskov/README.md
> +К существующей таблице accounts, нужно будет добавить fk_family_accounts(default=null).
СУБД postgresql, как я понимаю. как будет происходить взаимодействие с таблицей аккаунтов в монолите, если это изолированные базы данных?

2021-06-09 11:25 UTC, dr3w-an commented on alexandr-satskov/README.md
> +1. Включить для людей, что часто заказывают такси не для себя.
как это определить?

2021-06-09 11:25 UTC, dr3w-an commented on alexandr-satskov/api.yaml
> +    get:
разве не post?

2021-06-09 11:25 UTC, dr3w-an commented on alexandr-satskov/api.yaml
> +          description: "account has already been created"
а если другая ошибка возникла при создании? классическое описание `Bad request` сработало бы

2021-06-09 11:25 UTC, dr3w-an commented on alexandr-satskov/api.yaml
> +    get:
разве не delete?

2021-06-09 11:25 UTC, dr3w-an commented on alexandr-satskov/api.yaml
> +
а ответ на другие случаи? например, если аккаунт не найден

2021-06-09 11:25 UTC, dr3w-an commented on alexandr-satskov/api.yaml
> +              $ref: "#/components/schemas/UserDataValid"
ссылка на components есть, а самих components нет. без них схема не валидна

2021-06-09 11:25 UTC, dr3w-an commented on alexandr-satskov/api.yaml
> +                type: string
это тип чего?

2021-06-11 21:50 UTC, Skrillite requested changes
Потерялись ручки, реализующие логику оплаты

2021-06-11 21:50 UTC, Skrillite commented on alexandr-satskov/README.md
> +К существующей таблице accounts, нужно будет добавить fk_family_accounts(default=null).
Таблица с аккаунтами на данный момент скорее всего очень большая, поэтому менять её структуру будет супер дорого. К тому же, эта база вообще не из нашего микросервиса, да и пренадлежность пользователя к семейному аккаунту косвенно зависит от его учетных данных (нарушает 3НФ). Предлагаю создать отдельное отношение group_members из id пользователя и id семейного аккаунта

2021-06-11 21:50 UTC, Skrillite commented on alexandr-satskov/README.md
> +2. Кидать инвайт для вступления в семейный аккаунт
Добавление нового участника ведь входит в CRUD

2021-06-11 21:50 UTC, Skrillite commented on alexandr-satskov/README.md
> +4. Выбирать в качестве способа оплаты семейный аккаунт (/pay endpoint)
Ещё нужна логика CRUD для способа оплаты

2021-06-11 22:09 UTC, twinkleToes2001 commented on alexandr-satskov/README.md
> +1. Включить для людей, что часто заказывают такси не для себя.
полагаю, уже существует такая метрика

2021-06-11 22:11 UTC, twinkleToes2001 commented on alexandr-satskov/api.yaml
> +    get:
мы никаких данных туда не пушим, т.е. создаем сначала на создателе

2021-06-11 22:12 UTC, twinkleToes2001 commented on alexandr-satskov/api.yaml
> +          description: "account has already been created"
оки

2021-06-11 22:13 UTC, twinkleToes2001 commented on alexandr-satskov/api.yaml
> +
да, ты прав!

2021-06-11 22:13 UTC, twinkleToes2001 commented on alexandr-satskov/api.yaml
> +              $ref: "#/components/schemas/UserDataValid"
увидел

2021-06-11 22:14 UTC, twinkleToes2001 commented on alexandr-satskov/README.md
> +К существующей таблице accounts, нужно будет добавить fk_family_accounts(default=null).
крутое решение, спасибо!

2021-06-11 22:19 UTC, twinkleToes2001 commented on alexandr-satskov/README.md
> +2. Кидать инвайт для вступления в семейный аккаунт
Инвайт имеется ввиду генерация ссылки при переходе по которой будет происходить какая-то логика

2021-06-11 22:20 UTC, twinkleToes2001 commented on alexandr-satskov/README.md
> +4. Выбирать в качестве способа оплаты семейный аккаунт (/pay endpoint)
полагается, что она уже реализована, нет?

2021-06-11 22:31 UTC, Skrillite approved these changes
Гениально!

2021-06-11 22:32 UTC, merged