Решение для ДЗ №1
YaBackSchool2021/homework1 pull request #20
Opened 2021-06-08 14:20 UTC by tim-km

2021-06-09 08:12 UTC, key1c30 requested changes

2021-06-09 08:12 UTC, key1c30 commented on timur-khamatshin/openapi.yaml
> +  '/passenger-rating/calculate':
Зачем, если задача по расчету добавляется в очередь? Также вроде REST сервис делаешь а тут какой то action в пути

2021-06-09 08:12 UTC, key1c30 commented on timur-khamatshin/openapi.yaml
> +    PassengerRating:
Как проверяется личность водителя?

2021-06-09 09:41 UTC, tim-km commented on timur-khamatshin/README.md
> +- Отбрасывать экстремальные значения
Возникла идея, что если у пользователя почти 100% оценок 5 и их достаточно много, а в один момент прилетает 1, то оценка может быть не совсем объективной. Для этого еще можно вести некий рейтинг объективности оценок от водителя
![monitor](https://www.meme-arsenal.com/memes/0bc46513953fe9d550dae5be049c1da0.jpg)
Но сейчас подумал, что все это может быть слишком сложно и нецелесообразно, поэтому этот пункт могу убрать

2021-06-09 09:41 UTC, tim-km commented on timur-khamatshin/openapi.yaml
> +  '/passenger-rating/calculate':
По сути эта ручка и будет добавлять задачу расчета в очередь. Мне кажется она должна быть на случай каких-то сбоев в системе, чтобы мы могли в определенный момент запустить это вручную, а не только при проставлении оценки водителем. Думаю лучше расписать response по-другому, но могу и убрать метод полностью

2021-06-09 09:42 UTC, tim-km commented on timur-khamatshin/openapi.yaml
> +    PassengerRating:
Не совсем понял, предлагаешь описать здесь систему аутентификации?

2021-06-09 13:46 UTC, key1c30 commented on timur-khamatshin/openapi.yaml
> +    PassengerRating:
Скорее всего приложение к каждому запросу цепляет JWT токен и поэтому вопрос не актуален)

2021-06-09 13:47 UTC, key1c30 commented on timur-khamatshin/openapi.yaml
> +  '/passenger-rating/calculate':
Можно же добавлять в очередь задачу сразу при добавлении оценки, то что для админ панели это может пригодится это да, но пока не надо как я понимаю)

2021-06-09 13:49 UTC, key1c30 commented on timur-khamatshin/README.md
> +- Отбрасывать экстремальные значения
Будет вполне объективная оценка, пока нет такой проблемы и лучше не думать слишком наперед, я думаю

2021-06-09 18:00 UTC, nimusp requested changes

2021-06-09 18:52 UTC, tim-km commented on timur-khamatshin/README.md
> +| score | Оценка | Decimal
Теоретически можно поэкспериментировать с возможностью выставить десятичное значение и тогда не будет проблем с хранением. Но конечно стандарт - это целые числа от 1 до 5, согласен

2021-06-09 18:52 UTC, tim-km commented on timur-khamatshin/README.md
> +| passenger_id | Идентификатор пассажира | FK
passenger_id на мой взгляд точно будет не лишним, иначе как быстро посчитать среднюю оценку для одного пользователя? Таблица поездок скорее всего будет находится в совершенно другой БД, все же микросервисы. Тогда и driver_id пригодится, чтобы далеко не ходить. В любом случае, на первых этапах я бы не боялся избыточности данных

2021-06-09 18:52 UTC, tim-km commented on timur-khamatshin/README.md
> +- Проследим за метрикой трудоустройства новых водителей, проведем опрос среди нынешних
В самом 1 пункте я пишу тезис, что фича может позволить сервису стать более благоприятным для водителей. Более благоприятный сервис для работы -> больше водителей хотят к нам. В целом мне кажется нужно смотреть какие-то метрики для водителей, фича в первую очередь для них, а это лишь один из примеров. Других примеров не придумал

2021-06-09 19:08 UTC, nimusp commented on timur-khamatshin/README.md
> +| passenger_id | Идентификатор пассажира | FK
про passenger_id согласен, да
ну раз на избыточность без разницы, то тогда ок

2021-06-09 19:08 UTC, nimusp approved these changes

2021-06-10 08:07 UTC, key1c30 approved these changes

2023-02-28 20:46 UTC, closed without merging